AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for Next.js blog deployment on App Runner'

Resources:
  BlogDeploymentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
                - tasks.apprunner.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess'

  BlogECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: blog-template
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

  BlogAppRunnerService:
    Type: 'AWS::AppRunner::Service'
    Properties:
      ServiceName: blog-template
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt BlogDeploymentRole.Arn
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/blog-template:latest
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: 3000
      InstanceConfiguration:
        Cpu: 1024
        Memory: 2048

Outputs:
  AppRunnerServiceURL:
    Description: URL of the App Runner service
    Value: !GetAtt BlogAppRunnerService.ServiceUrl
  ECRRepositoryURI:
    Description: URI of the ECR repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/blog-template