name: Setup Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        default: 'dev'

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy CloudFormation Stack
        id: cloudformation
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/deploy-app-runner.yml \
            --stack-name ${{ github.event.inputs.environment }}-nextjs-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides Environment=${{ github.event.inputs.environment }}
            
      - name: Set repository and service secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get outputs from CloudFormation
          SERVICE_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.environment }}-nextjs-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`AppRunnerServiceArn`].OutputValue' \
            --output text)
          
          ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.environment }}-nextjs-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`ECRRepositoryURI`].OutputValue' \
            --output text)
          
          # Set secrets for the environment
          gh secret set "${{ github.event.inputs.environment }}_APP_RUNNER_SERVICE" -b "$SERVICE_ARN" --env ${{ github.event.inputs.environment }}
          gh secret set "${{ github.event.inputs.environment }}_ECR_REPOSITORY" -b "$ECR_URI" --env ${{ github.event.inputs.environment }}