name: 1. Setup Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        default: 'dev'

jobs:
  setup-base-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Pre-deployment Instructions
        run: |
          echo "=================================================="
          echo "🚀 Starting infrastructure setup process"
          echo "=================================================="
          echo "⚠️  IMPORTANT: After this workflow completes, you will need to:"
          echo "1. Go to your repository's Settings"
          echo "2. Navigate to Environments"
          echo "3. Select or create the '${{ github.event.inputs.environment }}' environment"
          echo "4. Add the ECR repository URI as a secret"
          echo "=================================================="
          
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy Base Infrastructure
        id: cloudformation
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/ecr-setup.yml \
            --stack-name ${{ github.event.inputs.environment }}-ecr-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides Environment=${{ github.event.inputs.environment }}
            
      - name: Get ECR Repository URI
        id: ecr
        run: |
          ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.environment }}-ecr-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`ECRRepositoryURI`].OutputValue' \
            --output text)
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      - name: Display Next Steps
        run: |
          echo "=================================================="
          echo "✅ Infrastructure setup completed successfully!"
          echo "=================================================="
          echo "⚠️  REQUIRED MANUAL STEPS:"
          echo "Please set up the following secret in your GitHub repository:"
          echo ""
          echo "1. Go to: Settings → Environments"
          echo "2. Select or create environment: '${{ github.event.inputs.environment }}'"
          echo "3. Add this secret:"
          echo "   Name: ECR_REPOSITORY_URI"
          echo "   Value: ${{ env.ECR_URI }}"
          echo ""
          echo "📋 Copy this value: ${{ env.ECR_URI }}"
          echo ""
          echo "Once you've added this secret, you can proceed with:"
          echo "1. Running the 'Build and Push Image' workflow"
          echo "2. Then running the 'Deploy to App Runner' workflow"
          echo "=================================================="